### ISSUE TITLE
ModuleNotFoundError: No module named '_Geom'

### ISSUE THREAD

**Issue by gerroon** [RomainGuimbal/SurfacePsycho#1]
Hi

I am gettign an error when installing on 4.1

![image](https://github.com/RomainGuimbal/SurfacePsycho/assets/8519469/de7da1d5-c4b3-42a5-bf61-50340b0545b8)

```
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: Module use of python310.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\blender\4.1\scripts\modules\addon_utils.py", line 380, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SurfacePsycho\__init__.py", line 38, in <module>
    from OCC.Core.Geom import Geom_BezierSurface, Geom_BSplineSurface, Geom_BezierCurve, Geom_Plane, Geom_TrimmedCurve #, Geom_BSplineCurve
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SurfacePsycho\OCC\Core\Geom.py", line 23, in <module>
    _Geom = swig_import_helper()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SurfacePsycho\OCC\Core\Geom.py", line 22, in swig_import_helper
    return importlib.import_module('_Geom')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_Geom'

```

**Comment by RomainGuimbal** [comment]
Hi, are you on Windows ?

**Comment by gerroon** [comment]
Hi

Yes I am on Win 11 x64

**Comment by RomainGuimbal** [comment]
Can you check if 0.3 gives the same error ?
If it doesn't work you can also try to install Visual Studio 2013 Runtime and Visual Studio Redistributable like specified for this addon that uses OCC too [https://ambient.gumroad.com/l/stepper?layout=profile](https://ambient.gumroad.com/l/stepper?layout=profile)

**Comment by RomainGuimbal** [comment]
By the way I just realized on blender 4.1, SP 0.3 will lack the button to bind the assets

**Comment by RomainGuimbal** [comment]
I confirm it doesn't work on 4.1 for the moment. Probably due to python3.11

**Comment by RomainGuimbal** [comment]
This was indeed the case, thanks for reporting, I close the issue and invite you to wait for the next alpha coming really soon :)
